version: '3'
services:
  jenkins:
    build: .
    ports:
    - '80:8080'
    - '443:8443'
    environment:
    - JENKINS_USERNAME=user
    - JENKINS_PASSWORD=secret
    volumes:
    - ./jenkins_home:/var/jenkins_home
