server:
  port: ${port:8765}

zuul:
  prefix: /api
  routes:
    client:
      path: /client/**
      serviceId: client-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false

