spring:
  application:
    name: order-service

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security:
    enabled: false
