spring:
  application:
    name: order-service
  cache:
    type: redis
  redis:
    host: localhost
    port: ${REDIS-PORT:6379}

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security:
    enabled: false

order:
  prefix: ${order.prefix:order}
