spring:
  application:
    name: order-service
  cache:
    type: redis
  redis:
    host: localhost
    port: ${REDIS-PORT:6379}

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#ribbon:
#    ReadTimeout: 3000
#    MaxAutoRetries: 3
#    MaxAutoRetriesNextServer: 3

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security:
    enabled: false
