spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: mongo
      password: sql

server:
  port: ${PORT:8070}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

product:
  prefix: ${PRODUCT-PREFIX:product}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security:
    enabled: false

