spring:
  application:
    name: product-service

server:
  port: ${PORT:8070}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

product:
  prefix: ${PRODUCT-PREFIX:product}
