server:
  port: ${PORT:8889}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlekseySamoylov/microservice-config.git
          search-paths: logging
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production

management:
  security:
    enabled: false

