version: '3.1'

services:

  mongo:
    image: bitnami/mongodb:4-ol-7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=sql
      - MONGODB_DATABASE=product

