spring:
  application:
    name: social
  datasource:
    url: jdbc:postgresql://localhost:5432/public_db
    username: db_user
    password: sql
  social:
    facebook:
      app-id: ######
      app-secret: ######
